services:
  app:
    image: node:14-alpine
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm start

volumes:
  dependencies: